### ISSUE TITLE
KeyError: 'Mask2FormerVideoCustomMatching is not in the models registry'

### ISSUE THREAD

**Issue by jiyuwangbupt** [lxtGH/Tube-Link#13]
Traceback (most recent call last):
  File "/home/wm/Tube-Link/tools/train.py", line 250, in <module>
    main()
  File "/home/wm/Tube-Link/tools/train.py", line 220, in main
    model = build_detector(
  File "/mnt/12T/wm/conda/bin/turbe0/lib/python3.9/site-packages/mmdet/models/builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "/mnt/12T/wm/conda/bin/turbe0/lib/python3.9/site-packages/mmcv/utils/registry.py", line 238, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/mnt/12T/wm/conda/bin/turbe0/lib/python3.9/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/mnt/12T/wm/conda/bin/turbe0/lib/python3.9/site-packages/mmcv/utils/registry.py", line 62, in build_from_cfg
    raise KeyError(
KeyError: 'Mask2FormerVideoCustomMatching is not in the models registry'.

(/mnt/12T/wm/conda/bin/turbe0) wm@RTX6000Server2:~/Tube-Link$ python
Python 3.9.12 (main, Jun  1 2022, 11:38:51) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mmdet
/mnt/12T/wm/conda/bin/turbe0/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
>>> mmdet.__version__
'2.28.2'
>>> import mmcv
>>> mmcv.__version__
'1.7.2'

(/mnt/12T/wm/conda/bin/turbe0) wm@RTX6000Server2:~/Tube-Link$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
(/mnt/12T/wm/conda/bin/turbe0) wm@RTX6000Server2:~/Tube-Link$ python
Python 3.9.12 (main, Jun  1 2022, 11:38:51) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'2.1.0+cu121'

**Comment by jorel666** [comment]
Hi @lxtGH! Hi @lxtGH — 14 AI repos? ARKHAN adds 59 more autonomous chips: scraping, outreach, crypto, delivery.

Starter: $6.50 — https://xipetotec.lemonsqueezy.com/checkout/buy/8f4322fc-f700-456c-8278-241ba4307ae6
Full API: https://xipetotec.lemonsqueezy.com/checkout/buy/d5943e3e-b661-4011-a995-826847b87156

Reply STOP to unsubscribe.

Pago directo USDT TRC20: TWJv7sD1nTWeHFsaMDBuJEEAc62VoxPmvm
Ref: pay_973551b2ac53

*Automated outreach — reply NO to stop.*
